RuneLabsxyz/PonziLand

client/.gitignore, client/src/lib/api/land.ts, client/src/lib/data.json, client/src/lib/interfaces.ts, client/src/lib/map/map.svelte, client/src/lib/map/tile.svelte, client/src/lib/stores.ts, client/src/lib/stores/camera.ts, client/src/lib/stores/stores.ts, client/src/lib/ui/buymodal.svelte, client/src/lib/ui/sidebar.svelte, client/src/lib/ui/tilehud.svelte, client/src/lib/ui/ui.svelte
=> front end 

client/src/lib/api/land.ts, client/src/lib/interfaces.ts, client/src/lib/map/map.svelte, client/src/lib/map/tile.svelte, client/src/lib/stores/stores.ts, client/src/lib/ui/auctionmodal.svelte, client/src/lib/ui/buymodal.svelte, client/src/lib/ui/tilehud.svelte, client/src/lib/ui/ui.svelte
Added:
- bidding modal (simple)
- improved the buy modal
- added the token address data in the land being sold
=> Front end improvements

contracts/.tool-versions, contracts/src/components/payable.cairo, contracts/src/models/land.cairo, contracts/src/systems/actions.cairo
Issue #52 
Now tracks stakes per land basis
=> Stake changes

contracts/src/components/payable.cairo, contracts/src/systems/actions.cairo
this pr resolve issue https://github.com/RuneLabsxyz/PonziLand/issues/56
With this function we can manage and show the data to the player more clearly
=> add get_next_claim_info()

client/src/lib/components/auction/auction-admin.svelte, client/src/routes/+page.svelte, client/src/routes/admin/+layout.server.ts, client/src/routes/admin/+page.svelte
=> add auction admin panel

contracts/src/components/payable.cairo, contracts/src/tests/actions.cairo
this resolve issue https://github.com/RuneLabsxyz/PonziLand/issues/73
=> refactor of tests

contracts/src/store.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo
=> add auction into nuke,

contracts/src/components/payable.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo
this pr resolve issue https://github.com/RuneLabsxyz/PonziLand/issues/81
=> add logic to initialize auctions for neighbors

contracts/src/components/payable.cairo, contracts/src/systems/actions.cairo
Closes  #86
We reuse the get_neighbors_yield logic to get the remaining share as well.
=> add logic for remaining stake

contracts/src/systems/actions.cairo
=> fix: TAX RATE return val

playtest/deploy.sh, playtest/tokens.json
feat: Added freshly created tokens addresses
=> fix: Fixed deployment script

contracts/src/consts.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo, contracts/src/tests/setup.cairo
Closes #106 
with this new logic we have to change the deploy to pass the token address
=> Set max auctions

contracts/src/consts.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo
=> add logic for do an auction for nuked lands

client/src/lib/components/buy/buy-modal.svelte, client/src/lib/components/wallet/wallet-balance.svelte
=> feat: Show price when buying land from player

contracts/src/models/auction.cairo, contracts/src/systems/actions.cairo
feat: Enforced the floor price * 10 as the min starting price
=> fix: Fixed the auction rate

contracts/src/components/payable.cairo
=> Fix:fixed the tax distribution for each neighbor

client/src/lib/components/wallet/wallet-lookup.svelte
=> feat: Added copy wallet function

client/src/lib/components/map/tile.svelte
=> fix: The crown disappears when the account changes

client/src/lib/components/wallet/SwitchChainModal.svelte, client/src/lib/contexts/account.ts, client/src/lib/stores/stores.svelte.ts, client/src/routes/game/+page.svelte, contracts/manifest_sepolia.json
=> feat: Enforce the network to be the one for the deployment

client/src/lib/components/map/map.svelte, client/src/lib/stores/camera.ts
from CDG Terminal 2 MacDonald's
=> fix: camera max zoom #131

client/src/lib/api/land.svelte.ts, client/src/lib/components/land/hud/land-hud-other.svelte, client/src/lib/components/land/hud/land-hud-owned.svelte, client/src/lib/contexts/store.ts, client/src/lib/contracts.gen.ts, client/src/lib/dojoConfig.ts, client/src/lib/models.gen.ts, client/src/lib/utils/level.ts, contracts/bindings/typescript/contracts.gen.ts, contracts/manifest_sepolia.json, contracts/src/systems/actions.cairo
There's also modifications in the contract, to make sure that only the owner can call levelup, and that it requires a wallet account to do.
=> feat: Frontend support for land level ups

client/src/lib/components/auction/auction-modal.svelte, client/src/lib/components/buy/buy-sell-form.svelte, client/src/lib/components/land/land-display.svelte, client/src/lib/components/land/land-info-card.svelte, client/src/lib/components/land/land-overview.svelte, client/src/lib/components/toolbar/toolbar-drawer-auctions.svelte, client/src/lib/components/toolbar/toolbar-drawer-lands.svelte, client/src/lib/components/toolbar/toolbar-drawer.svelte, client/src/lib/stores/stores.svelte.ts
still need to fix double loading of auctions
=> 187 rune 109 auctions panel

contracts/src/components/stake.cairo, contracts/src/components/taxes.cairo, contracts/src/consts.cairo, contracts/src/models/auction.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo, contracts/src/utils/get_neighbors.cairo, contracts/src/utils/spiral.cairo
Added new function to get the average sell price from neighbors for nuked lands
=> [RUNE-124] - fix: add logic to get the average sell price for nuked lands

client/src/lib/account.svelte.ts, client/src/routes/game/+page.svelte, devenv.nix, devenv.yaml
Made sure that the socialink cheks are made before clearing the login. Avoids the "please select a username" popup from appearing for a few seconds when loading the game.
=> fix: Made login screen wait for socialink checking

client/src/lib/accounts/social/index.svelte.ts, client/src/lib/components/socialink/Invitation.svelte, client/src/lib/components/socialink/register.svelte, client/src/lib/components/wallet/SwitchChainModal.svelte, client/src/routes/game/+page.svelte
Improved username handling in social registration and adjusted modal z-index values
- Usernames are now converted to lowercase before processing
- Removed redundant username field from registration payload
- Added console logging for signature requests
- Adjusted z-index values for registration and invitation modals
- Moved SwitchChainModal outside of the main game UI conditional rendering
- Added debug inspection for chain switching visibility
Closes #219
=> feat: Added back chain modal on register

client/src/lib/components/ramp/character-box.svelte, client/src/lib/components/ui/image-if-available.svelte, client/src/lib/server/layerswap/index.ts, client/src/routes/ramp/+layout.svelte, client/src/routes/ramp/+page.svelte, client/src/routes/ramp/RampTokenSelect.svelte, client/src/routes/ramp/[swapId]/+page.svelte
fix(style): Applied updated styles for the new font
=> fix: Fixed layerswap system

client/src/routes/onboarding/deploy/+page.svelte
Improved wording for the deployment page.
=> feat: Improved wording for deployment

client/src/lib/components/dashboard/PriceChart.svelte
Invert function for correct price display
=> fix: dashboard graphs

client/package.json, client/src/hooks.server.test.ts, client/src/hooks.server.ts, client/src/lib/const.ts, client/src/routes/maintenance/+page.svelte, client/vitest.config.ts
Also added tests for that specific function as they are the bane of my existence and broke prod more than once because of time gates.
=> feat: Added end time to maintenance page

contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo
this resolve issue #235 
We pass the auction function to internalTrait and modify the tests so we can test each function individually regardless of changes in the auction expansion
=> refactor: make auction function internal and modify tests

contracts/src/models/auction.cairo
=> Use linear decay rate for the first minutes

contracts/src/systems/actions.cairo
this pr resolves #277 and #236
=> make nuke internal and fix issue with invalid lp

.github/workflows/client-cloudflare.yaml, .github/workflows/client-formatting.yaml, .github/workflows/contracts-formatting.yaml, .github/workflows/contracts-test.yaml
This is useful for graphite stacked PRs
=> ci: Run all workflows on any pr target

client/src/lib/components/land/land-tax-claimer.svelte, client/src/lib/stores/claim.svelte.ts
=> change claim_all() for claim() for each land from the coin icon

contracts/src/components/taxes.cairo, contracts/src/consts.cairo, contracts/src/helpers/circle_expansion.cairo, contracts/src/helpers/coord.cairo, contracts/src/models/auction.cairo, contracts/src/models/land.cairo, contracts/src/store.cairo, contracts/src/systems/actions.cairo, contracts/src/tests/actions.cairo, contracts/src/tests/setup.cairo, contracts/src/utils/common_strucs.cairo, contracts/src/utils/get_neighbors.cairo, contracts/src/utils/level_up.cairo, contracts/src/utils/spiral.cairo
=> reduce costs storage from u64 to u16

Cargo.lock, contracts/manifest_sepolia.json, crates/ekubo/Cargo.toml, crates/ekubo/examples/get_price.rs, crates/ekubo/src/api/pool.rs, crates/ekubo/src/lib.rs, crates/ekubo/src/math/u256fd128.rs, crates/ekubo/src/price.rs, crates/indexer/Cargo.toml, crates/indexer/config.toml, crates/indexer/src/config.rs, crates/indexer/src/main.rs, crates/indexer/src/monitoring/mod.rs, crates/indexer/src/monitoring/namespace_layer.rs, crates/indexer/src/routes/mod.rs, crates/indexer/src/routes/price/mod.rs, crates/indexer/src/routes/tokens/mod.rs, crates/indexer/src/service/ekubo.rs, crates/indexer/src/service/mod.rs, crates/indexer/src/service/token.rs, crates/indexer/src/state.rs, crates/indexer/src/worker/mod.rs
feat: Implemented cron task handling
feat: Implemented monitoring for cron task handling
=> feat: Implemented ekubo pricing subsystem
